$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
import:
  - https://cdn.jsdelivr.net/npm/@cspell/dict-fr-fr/cspell-ext.json
language: fr, fr_FR
words:
  - Symfony
