### Ping
GET http://localhost/ping

### Prometheus metrics
GET http://localhost/metrics


### whoami : 301 moved Permanently -> https
GET http://localhost/whoami

### whoami : 301 moved Permanently -> /
GET https://localhost/whoami

### whoami
GET https://localhost/whoami/

### whoami
GET https://localhost/whoami?wait=10s



### api (réponse au format json)
GET https://localhost/whoami/api?env=true


### data
GET https://localhost/whoami/data?size=1000


### health write
POST https://localhost/whoami/health

474

### health read
HEAD https://localhost/whoami/health

### bench
HEAD https://localhost/whoami/bench
