services:
   # https://hub.docker.com/_/mongo
   mongodb:
     image: mongodb/mongodb-community-server:8.3-ubi9-slim
     restart: no
     ports:
      - 27017:27017
     environment:
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
