services:
  web:
    image: odoo:19
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  db:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
    volumes:
      - db:/var/lib/postgresql
    secrets:
      - postgresql_password

volumes:
  web:
  db:

secrets:
  postgresql_password:
    file: pg_pass
